services:
  database:
    image: postgres
    command: >-
      postgres
      -c shared_preload_libraries='pg_stat_statements'
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
