default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  username: root
  password: root
  port: 5432
  database: ibimash_development

test:
  <<: *default
  host: localhost
  username: root
  password: root
  port: 5432
  database: ibimash_test

production:
  <<: *default
  database: ibimash_production
  username: root
  password: <%= ENV["PRODUCTION_DATABASE_PASSWORD"] %>
